---
title: "ADS_11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

This R markdown document contains code worked upon as part of the ADS Lesson 11


## Importing the required liraries
```{r}
library(purrr)
library(ggplot2)
```

```{r}
x <- c(1,2,3,4,5,6,7,8,9,10)
y <- c(26,-11,45,73,18,4,-1,33,91,59)
lineup <- data.frame(Xnum=x,Ynum=y)
model <- kmeans(x = lineup, centers = 2)
model$tot.withinss
```
## R elbow Plot
```{r}
tot_withinss <- map_dbl(1:8, function(k){
  model <- kmeans(x = lineup, centers = k)
  model$tot.withinss
})
head(tot_withinss)
elbow_df <- data.frame(
  k=1:8,
  tot_withinss = tot_withinss
)
print(elbow_df)
ggplot(elbow_df,aes(x=k,y=tot_withinss)) +
  geom_line()
```
## Understanding K Means. creating 2 centroid and 3 centroid clusters on same data
```{r}
set.seed(1234)
x <- rnorm(12, mean = rep(1:3, each = 4), sd = 0.2)
y <- rnorm(12, mean = rep(c(1, 2, 1), each = 4), sd = 0.2)
plot(x, y, col = "blue", pch = 19, cex = 2)
text(x + 0.05, y + 0.05, labels = as.character(1:12))
dffrm <- data.frame(x,y)
kmeansobj2 <- kmeans(dffrm, centers = 2)
kmeansobj3 <- kmeans(dffrm, centers = 3)
kmeansobj2$cluster
kmeansobj3$cluster
```
## Plotting Heat Map
```{r}
set.seed(634)
dataMatrix <- as.matrix(dffrm)[sample(1:12), ]
head(dataMatrix)
kmeansObj <- kmeans(dataMatrix, centers = 3)
par(mfrow = c(1, 2))
image(t(dataMatrix)[, nrow(dataMatrix):1], yaxt = "n", main = "Original Data")
image(t(dataMatrix)[, order(kmeansObj$cluster)], yaxt = "n", main = "Clustered Data")
```
# Assignment Questions
## Calculating Distances
```{r}
a <- c(3,4,7,8)
b <- c(5,7,7,6)
distMatrix <- matrix(c(a,b), byrow=T,nrow=2)
manh<-dist(distMatrix, method="manhattan")
eul<-dist(distMatrix, method="euclidean")
manh
eul
```

## mtcars elbow Plot
```{r mtcars}
head(mtcars)
tot_withinss <- map_dbl(1:8, function(k){
  model <- kmeans(x = mtcars, centers = k)
  model$tot.withinss
})
head(tot_withinss)
elbow_df <- data.frame(
  k=1:8,
  tot_withinss = tot_withinss
)
print(elbow_df)
ggplot(elbow_df,aes(x=k,y=tot_withinss)) +
  geom_line()
```
## cars analysis
```{r cars}
head(cars)
car_linr_model=lm(dist ~ speed, data = cars)
qqnorm(resid(car_linr_model))
shapiro.test(resid(car_linr_model))
```
